const KEY = 'clubBajoneroAdmin';
const images = {
  promo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
  burger: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=400&q=80',
  hero: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1400&q=85'
};
const initialState = { promos: [
  {id:1,title:'ABRIMOS',description:'Estamos de 20 a 22',image:images.promo,active:true},
  {id:2,title:'TAKE AWAY',description:'Pedí y retirá sin esperas',image:images.burger,active:true},
  {id:3,title:'PROMOS',description:'Del club siempre gana',image:images.promo,active:true},
  {id:4,title:'CLUB BAJONERO',description:'Más que una hamburguesa, es el club.',image:images.burger,active:true}
], products: [
  {id:1,title:'TRIPLE CARNE',description:'3 carnes con queso derretido y salsas...',price:350,image:images.burger,active:true},
  {id:2,title:'CLUB BACON',description:'Doble carne, bacon, cheddar, lechuga...',price:320,image:images.burger,active:true},
  {id:3,title:'SMASH CLÁSICA',description:'Carne smash, queso, cebolla, pepinillos...',price:280,image:images.burger,active:true},
  {id:4,title:'POLLO CRISPY',description:'Pollo crispy, lechuga, mayo de la casa...',price:290,image:images.burger,active:true}
], hero:{title:'HAMBURGUESAS DE OTRO NIVEL',subtitle:'HECHAS CON ACTITUD',description:'En Club Bajonero no hacemos hamburguesas comunes. Hacemos las que te hacen volver.',button:'VER MENÚ',image:images.hero}, button:{text:'VER MENÚ',link:'#menu',enabled:true}, about:{title:'Más que una hamburguesa, es el club.',description:'Un lugar para compartir, comer rico y volver siempre.',image:images.burger,extra:'Hechas con actitud.'}, footer:{instagram:'https://instagram.com',facebook:'https://facebook.com',tiktok:'https://tiktok.com',whatsapp:'https://wa.me/59800000000',text:'Club Bajonero',tagline:'Más que una hamburguesa, es el club.'}, settings:{businessName:'Club Bajonero',logo:'',primary:'#2d5bd2',secondary:'#ff741d',darkMode:true,contact:'Montevideo, Uruguay'}, updated:'Hoy, 17:20'};
let state = loadState();
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
function loadState(){try{return {...initialState,...JSON.parse(localStorage.getItem(KEY))};}catch{return structuredClone(initialState)}}
function saveState(message='Cambios guardados'){state.updated = `Hoy, ${new Date().toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'})}`;localStorage.setItem(KEY,JSON.stringify(state));render();toast(message)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2500)}
const titles={dashboard:['Dashboard','Gestioná el contenido de la página principal'],hero:['Inicio / Hero','Configurá el contenido principal de tu página'],promos:['Promos (Cards)','Gestioná las tarjetas de promociones'],products:['Menú (Modal)','Gestioná los productos del menú'],menu:['Menú Modal (Ver Menú)','Elegí qué productos aparecen y ordenalos'],button:['Botón Ver Menú','Configurá el llamado a la acción de tu página'],about:['Nosotros','Contale a tus clientes la historia del club'],footer:['Footer / Redes','Administrá tus enlaces y frases finales'],settings:['Configuración','Personalizá la identidad del panel y del sitio']};
function navigate(view){$$('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view && el.classList.contains('nav-item')));$('#page-title').textContent=titles[view]?.[0]||'Dashboard';$('#page-subtitle').textContent=titles[view]?.[1]||'';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function render(){
  $('#stat-promos').textContent=state.promos.filter(item=>item.active).length;$('#stat-products').textContent=state.products.length;$('#stat-updated').textContent=state.updated;
  $('#hero-preview-mini').src=state.hero.image;['title','subtitle','description','button'].forEach(key=>{$(`#hero-${key}-mini`).value=state.hero[key]});
  $('#dashboard-promos').innerHTML=state.promos.slice(0,4).map(compactPromo).join('');$('#dashboard-products').innerHTML=state.products.slice(0,4).map(compactProduct).join('');
  $('#promos-list').innerHTML=state.promos.map(item=>dataRow(item,'promo')).join('');$('#products-list').innerHTML=state.products.map(item=>dataRow(item,'product')).join('');
  $('#menu-list').innerHTML=state.products.map(item=>dataRow(item,'menu')).join('');$('#menu-count').textContent=`${state.products.filter(item=>item.active).length} activos`;
  fillForm($('#hero-form'),state.hero);fillForm($('#button-form'),state.button);fillForm($('#about-form'),state.about);fillForm($('#footer-form'),state.footer);fillForm($('#settings-form'),state.settings);updatePreviews();
}
function compactPromo(item){return `<div class="list-row"><img src="${item.image}" alt=""><div class="row-info"><strong>${item.title}</strong><small>${item.description}</small></div><span class="status ${item.active?'':'off'}">${item.active?'Activa':'Inactiva'}</span><div class="row-actions"><button class="icon-btn edit" data-action="edit-promo" data-id="${item.id}" aria-label="Editar"><i class="fa-solid fa-pen"></i></button><button class="icon-btn delete" data-action="delete-promo" data-id="${item.id}" aria-label="Eliminar"><i class="fa-regular fa-trash-can"></i></button></div></div>`}
function compactProduct(item){return `<div class="list-row"><img src="${item.image}" alt=""><div class="row-info"><strong>${item.title}</strong><small>${item.description}</small><b class="price">$${item.price}</b></div><span class="status ${item.active?'':'off'}">${item.active?'Activo':'Inactivo'}</span><div class="row-actions"><button class="icon-btn edit" data-action="edit-product" data-id="${item.id}" aria-label="Editar"><i class="fa-solid fa-pen"></i></button><button class="icon-btn delete" data-action="delete-product" data-id="${item.id}" aria-label="Eliminar"><i class="fa-regular fa-trash-can"></i></button></div></div>`}
function dataRow(item,type){const product=type!=='promo';return `<div class="list-row"><img src="${item.image}" alt=""><div class="row-info"><strong>${item.title}</strong><small>${item.description}</small>${product?`<b class="price">$${item.price}</b>`:''}</div><span class="status ${item.active?'':'off'}">${item.active?'Activo':'Inactivo'}</span><div class="row-actions">${type==='menu'?`<button class="icon-btn" data-action="move-up" data-id="${item.id}" title="Subir"><i class="fa-solid fa-arrow-up"></i></button><button class="icon-btn" data-action="toggle-product" data-id="${item.id}" title="Activar o desactivar"><i class="fa-solid fa-power-off"></i></button>`:`<button class="icon-btn edit" data-action="edit-${type}" data-id="${item.id}" aria-label="Editar"><i class="fa-solid fa-pen"></i></button><button class="icon-btn delete" data-action="delete-${type}" data-id="${item.id}" aria-label="Eliminar"><i class="fa-regular fa-trash-can"></i></button>`}</div></div>`}
function fillForm(form,data){if(!form)return;Object.entries(data).forEach(([key,value])=>{const input=form.elements[key];if(input)input.type==='checkbox'?input.checked=value:input.value=value})}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function updatePreviews(){const h=state.hero;$('#hero-preview').src=h.image;$('#preview-title').textContent=h.title;$('#preview-subtitle').textContent=h.subtitle;$('#preview-description').textContent=h.description;$('#preview-button').textContent=h.button;const a=state.about;$('#about-preview-image').src=a.image;$('#about-preview-title').textContent=a.title;$('#about-preview-description').textContent=a.description}
function openModal(type,item={}){const isPromo=type==='promo';const title=item.id?`Editar ${isPromo?'promo':'producto'}`:`Nueva ${isPromo?'promo':'producto'}`;$('#modal-content').innerHTML=`<h2>${title}</h2><p>Completá los datos para actualizar tu página.</p><form id="item-form" class="form-stack"><label>Imagen (URL)<input name="image" type="url" value="${item.image|| (isPromo?images.promo:images.burger)}"></label><label>${isPromo?'Título':'Nombre'}<input name="title" required value="${item.title||''}"></label><label>Descripción<textarea name="description" required>${item.description||''}</textarea></label>${isPromo?'':'<label>Precio<input name="price" type="number" min="0" required value="'+(item.price||'')+'"></label>'}<label class="switch-label"><input name="active" type="checkbox" ${item.active!==false?'checked':''}><span class="switch"></span> Activo</label><div class="modal-actions"><button type="button" class="ghost-btn" data-action="close-modal">Cancelar</button><button type="submit" class="primary-btn">Guardar ${isPromo?'Promo':'Producto'}</button></div></form>`;$('#modal-backdrop').classList.add('open');$('#modal-backdrop').setAttribute('aria-hidden','false');$('#item-form').onsubmit=e=>{e.preventDefault();const data=formData(e.target);data.active=e.target.elements.active.checked;data.price=Number(data.price||0);const collection=isPromo?'promos':'products';if(item.id)state[collection]=state[collection].map(entry=>entry.id===item.id?{...entry,...data}:entry);else state[collection].push({id:Date.now(),...data});closeModal();saveState(item.id?`${isPromo?'Promo':'Producto'} actualizado`:`${isPromo?'Promo':'Producto'} creado correctamente`)}}
function closeModal(){$('#modal-backdrop').classList.remove('open');$('#modal-backdrop').setAttribute('aria-hidden','true')}
function confirmDelete(type,id){const collection=type==='promo'?'promos':'products';const item=state[collection].find(entry=>entry.id===id);$('#modal-content').innerHTML=`<h2>Eliminar ${type==='promo'?'promo':'producto'}</h2><p>¿Estás seguro de que querés eliminar “${item.title}”?</p><div class="modal-actions"><button class="ghost-btn" data-action="close-modal">Cancelar</button><button class="danger-btn" data-action="confirm-delete" data-type="${type}" data-id="${id}">Eliminar</button></div>`;$('#modal-backdrop').classList.add('open')}
function bindForm(id,key,message){const form=$(id);form.addEventListener('submit',event=>{event.preventDefault();const data=formData(form);if(form.elements.enabled)data.enabled=form.elements.enabled.checked;if(form.elements.darkMode)data.darkMode=form.elements.darkMode.checked;state[key]={...state[key],...data};saveState(message)})}
document.addEventListener('click',event=>{const target=event.target.closest('[data-view],[data-action]');if(!target)return;if(target.dataset.view)navigate(target.dataset.view);const action=target.dataset.action;if(action==='new-promo')openModal('promo');if(action==='new-product')openModal('product');if(action==='edit-promo')openModal('promo',state.promos.find(x=>x.id===Number(target.dataset.id)));if(action==='edit-product')openModal('product',state.products.find(x=>x.id===Number(target.dataset.id)));if(action==='delete-promo')confirmDelete('promo',Number(target.dataset.id));if(action==='delete-product')confirmDelete('product',Number(target.dataset.id));if(action==='close-modal')closeModal();if(action==='confirm-delete'){const collection=target.dataset.type==='promo'?'promos':'products';state[collection]=state[collection].filter(x=>x.id!==Number(target.dataset.id));closeModal();saveState(`${target.dataset.type==='promo'?'Promo':'Producto'} eliminada`)}if(action==='toggle-product'){const item=state.products.find(x=>x.id===Number(target.dataset.id));item.active=!item.active;saveState('Estado del producto actualizado')}if(action==='move-up'){const index=state.products.findIndex(x=>x.id===Number(target.dataset.id));if(index>0)[state.products[index-1],state.products[index]]=[state.products[index],state.products[index-1]];saveState('Orden actualizado')}});
$('#modal-close').addEventListener('click',closeModal);$('#modal-backdrop').addEventListener('click',event=>{if(event.target.id==='modal-backdrop')closeModal()});$('#mobile-menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});bindForm('#hero-form','hero','Cambios del hero guardados');bindForm('#button-form','button','Botón actualizado');bindForm('#about-form','about','Nosotros actualizado');bindForm('#footer-form','footer','Footer actualizado');bindForm('#settings-form','settings','Configuración guardada');render();
